//array of objects
const list = [
    {
        id: 1,
        title: "My First Book of Pencil Control",
        author: "by Wonder House Books | 25 April 2018",
        price: 89,
        img: "https://littlelearns.com/wp-content/uploads/2022/07/Peppa-Pig-My-First-Book-Of-Patterns-Pencil-Control.jpg",
        amount: 1,
    },
    {
        id: 2,
        title: "108 Panchatantra Stories",
        author: "by Maple Press  | 1 September 2020",
        price: 98,
        img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 3,
        title: "Amazing Questions & Answers Science",
        author: "by Om Books Editorial Team  | 25 November 2018",
        price: 143,
        img: "https://5.imimg.com/data5/SELLER/Default/2023/1/OP/IL/WB/52610783/encyclopedia-amazing-questions-answers-science-500x500.jpg",
        amount: 1,
    },
    {
        id: 4,
        title: "My First Book of Pencil Control",
        author: "by Wonder House Books | 25 April 2018",
        price: 57,
        img: "https://littlelearns.com/wp-content/uploads/2022/07/Peppa-Pig-My-First-Book-Of-Patterns-Pencil-Control.jpg",
        amount: 1,
    },
    {
        id: 5,
        title: "My First 1000 Words",
        author: "by Wonder House Books  | 1 January 2018",
        price: 149,
        img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 6,
        title: "101 Panchatantra Stories for Children",
        author: "by Om Books Editorial Team | 30 September 2020",
        price: 135,
        img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 7,
        title: "Pre-School Activities Pack ",
        author: "by Om Books Editorial Team  | 1 January 2021",
        price: 693,
        img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 8,
        title: "Early Learning Library Pack 1",
        author: "by Wonder House Books  | 6 December 2020",
        price: 289,
        img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 9,
        title: "Blossom Moral Story Book for Kids ",
        author: "by Content Team at Target Publications",
        price: 80,
        img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 10,
        title: "Brain Activity Book for Kids",
        author: "by Maple Press | 1 September 2021",
        price: 86,
        img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 11,
        title: "Willy the Silly Panda",
        author: "by Rebecca Smith  | 14 December 2021",
        price: 120,
        img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 12,
        title: "Grandma's Bag of Stories",
        author: "by Sudha Murty | 1 January 2015",
        price: 157,
        img: "https://m.media-amazon.com/images/I/71R9Iixk7xL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 13,
        title: "The Jungle Book",
        author: "by Rudyard Kipling | 30 August 2016",
        price: 120,
        img: "https://upload.wikimedia.org/wikipedia/en/1/1d/Thejunglebook_movieposter.jpg",
        amount: 1,
    },
    {
        id: 14,
        title: "Goodnight Moon",
        author: "by Margaret Wise Brown | 3 March 2015",
        price: 180,
        img: "https://media.npr.org/assets/img/2022/09/01/gnm_9780060775858_10-1--8f0ca43498b3db4ca1bf7712cf41a7e46e896fc0.jpg?s=1100&c=50&f=jpeg",
        amount: 1,
        
    },
    {
        id: 15,
        title: "The Very Hungry Caterpillar",
        author: "by Eric Carle | 23 October 2019",
        price: 140,
        img: "https://m.media-amazon.com/images/I/81qsstEtrgL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 16,
        title: "The Gruffalo",
        author: "by Julia Donaldson | 7 April 2005",
        price: 160,
        img: "https://upload.wikimedia.org/wikipedia/en/thumb/3/34/Fairuse_Gruffalo.jpg/200px-Fairuse_Gruffalo.jpg",
        amount: 1,
    },
    {
        id: 17,
        title: "Where the Wild Things Are",
        author: "by Maurice Sendak | 15 November 1984",
        price: 199,
        img: "https://m.media-amazon.com/images/I/A1wx+e0rJ2L._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 18,
        title: "Charlotte's Web",
        author: "by E. B. White | 15 October 1952",
        price: 130,
        img: "https://m.media-amazon.com/images/I/813AS1xuZiL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 19,
        title: "The Cat in the Hat",
        author: "by Dr. Seuss | 12 March 1957",
        price: 115,
        img: "https://m.media-amazon.com/images/I/81sE-fprQ2L._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 20,
        title: "Guess How Much I Love You",
        author: "by Sam McBratney | 14 September 2010",
        price: 125,
        img: "https://m.media-amazon.com/images/I/A1TcIhEGV9L._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 21,
        title: "Matilda",
        author: "by Roald Dahl | 3 October 2013",
        price: 145,
        img: "https://upload.wikimedia.org/wikipedia/en/3/39/Matilda-Mara-Wilson.webp",
        amount: 1,
    },
    {
        id: 22,
        title: "The Adventures of Tom Sawyer",
        author: "by Mark Twain | 25 February 2009",
        price: 150,
        img: "https://www.loyalbooks.com/image/detail/49.jpg",
        amount: 1,
    },
    {
        id: 23,
        title: "Alice's Adventures in Wonderland",
        author: "by Lewis Carroll | 1 May 2018",
        price: 160,
        img: "https://m.media-amazon.com/images/I/71Uj9TYDQXL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 24,
        title: "The Tale of Peter Rabbit",
        author: "by Beatrix Potter | 15 January 2002",
        price: 135,
        img: "https://m.media-amazon.com/images/I/91oYLHFF8SL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 25,
        title: "Harry Potter and the Philosopher's Stone",
        author: "by J.K. Rowling | 26 June 1997",
        price: 499,
        img: "https://m.media-amazon.com/images/I/81q77Q39nEL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 26,
        title: "Percy Jackson and the Olympians: The Lightning Thief",
        author: "by Rick Riordan | 1 March 2006",
        price: 399,
        img: "https://m.media-amazon.com/images/M/MV5BZDE4M2ZiYzEtODJiZC00NmI1LWFlNTgtOGJlNTY3NmExYWNjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        amount: 1,
    },
    {
        id: 27,
        title: "Diary of a Wimpy Kid",
        author: "by Jeff Kinney | 1 April 2007",
        price: 300,
        img: "https://m.media-amazon.com/images/I/81R2N4PRuUL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 28,
        title: "The Hobbit",
        author: "by J.R.R. Tolkien | 21 September 1937",
        price:"https://m.media-amazon.com/images/I/71jKeGU9nKL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 29,
        title: "The Lion, the Witch and the Wardrobe",
        author: "by C.S. Lewis | 16 October 1950",
        price: 370,
        img: "https://m.media-amazon.com/images/I/81gGu7UdZ2L._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 30,
        title: "Charlie and the Chocolate Factory",
        author: "by Roald Dahl | 1 January 1964",
        price: 260,
        img: "https://m.media-amazon.com/images/I/81Dp5Of3zeL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
    {
        id: 31,
        title: "The Wind in the Willows",
        author: "by Kenneth Grahame | 29 October 2009",
        price: 180,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiDcLbVDpwvKlh3BqDOcryo47opvb9-IRGZw&s",
        amount: 1,
    },
    {
        id: 32,
        title: "The Little Prince",
        author: "by Antoine de Saint-Exupéry | 6 April 1943",
        price: 299,
        img: "https://m.media-amazon.com/images/I/71OZY035QKL._AC_UF1000,1000_QL80_.jpg",
        amount: 1,
    },
];
    

export default list;